@startuml C4
'
' C4-PlantUML
' C4-PlantUML combines the benefits of PlantUML and the C4 model 
' for providing a simple way of describing and communicate software architectures,
' especially during up-front design sessions – with an intuitive language 
' using open source and platform independent tools.
' forked to https://github.com/johnholliday/C4-PlantUML
'
!define C4PlantUml https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master
!include C4PlantUml/C4_Context.puml
!include C4PlantUml/C4_Container.puml
!include C4PlantUml/C4_Component.puml
!include C4PlantUml/C4_Dynamic.puml
!include C4PlantUml/C4_Deployment.puml

'
' Azure-PlantUML
' PlantUML sprites, macros and stereotypes for creating PlantUML diagrams with Azure components.
' forked to https://github.com/johnholliday/Azure-PlantUML
'
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!include AzurePuml/AzureCommon.puml
!include AzurePuml/AzureC4Integration.puml

!include AzurePuml/Web/all.puml
!include AzurePuml/Databases/all.puml
!include AzurePuml/DevOps/all.puml
!include AzurePuml/Identity/all.puml
!include AzurePuml/Networking/all.puml
!include AzurePuml/Containers/all.puml
!include AzurePuml/Compute/all.puml
!include AzurePuml/Analytics/all.puml
!include AzurePuml/Storage/all.puml
!include AzurePuml/Security/all.puml

'
' OfficePuml
' Common icons for diagramming M365/Azure architectures.
' forked to https://github.com/johnholliday/plantuml-office
'
!define OfficePuml https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!include OfficePuml/Servers/database_server.puml
!include OfficePuml/Servers/application_server.puml
!include OfficePuml/Clouds/cloud_sharepoint_online.puml
!include OfficePuml/Clouds/cloud_exchange_online.puml
!include OfficePuml/Clouds/office_365_cloud.puml
!include OfficePuml/Communications/shared_mailbox.puml
!include OfficePuml/Communications/site_mailbox.puml
!include OfficePuml/Communications/system_mailbox.puml
!include OfficePuml/Communications/user_mailbox.puml
!include OfficePuml/Communications/video_workload.puml
!include OfficePuml/Communications/voice_workload.puml
!include OfficePuml/Communications/discovery_search_mailbox.puml
!include OfficePuml/Communications/chat_room.puml
!include OfficePuml/Security/policy.puml
!include OfficePuml/Security/retention_policy.puml
!include OfficePuml/Security/retention_policy_tag.puml
!include OfficePuml/Security/role_assignment_policy.puml
!include OfficePuml/Security/role_group.puml
!include OfficePuml/Security/sharing_policy.puml
!include OfficePuml/Security/token.puml
!include OfficePuml/Security/token_service.puml
!include OfficePuml/Security/universal_security_group.puml
!include OfficePuml/Sites/site_collection.puml
!include OfficePuml/Sites/site_shared.puml
!include OfficePuml/Sites/site_team.puml
!include OfficePuml/Sites/subsite.puml
!include OfficePuml/Sites/website.puml
!include OfficePuml/Sites/my_site.puml

@enduml
